import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/navbar/Navbar";
import { getServerSession } from "next-auth";
import AuthProvider from "@/utils/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>
          {/* Start Navbar */}
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
